pipelines:
  default:
    - step:
        script:
          - echo "Starting tests!"
          - add-apt-repository ppa:ubuntu-lxc/lxd-stable
          - apt-get update
          - apt-get install golang -y
          - apt-get install llvm-runtime -y
          - git clone https://github.com/sstephenson/bats.git
          - cd bats
          - ./install.sh /usr/local
          - export GOPATH="/go"
          - mkdir -p /go/src/bitbucket.com/bongo227/furlang
          - cd /go/src/bitbucket.com/bongo227/furlang
          - mv /opt/atlassian/bitbucketci/agent/build/* ./
          - go get ./...
          - go get honnef.co/go/unused/cmd/unused
          - go build
          - go test ./...
          - bash runTests.sh --tap
          - unused ./...